config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"

  resources :journals do
    member do
      get "articles"
    end
  end
  devise_for :users
  resources :articles, :except => [:new] do
    member do
      get "new",:as => "new"
    end
  end
  resources :comments, :only => [:new,:create,:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :journal
  has_many :comments
  validates :title ,:presence => { :message => "can not be blank." },length: { in: 1..30 }
  validates :body ,:presence => { :message => "can not be blank." }
  validates :author ,:presence => { :message => "can not be blank." },length: { in: 1..30 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  has_ancestry
  validates :user_id, :body,:article_id, :presence => true
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :user
  has_many :articles
  validates :name ,:presence => { :message => "can not be blank." },length: { in: 1..30 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :journals
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = Comment.new(:article_id => @article.id) if @article.present?
    # @comments = Comment.where(:article_id => @article.id,:ancestry=>nil).order("created_at asc") if @article.present?
    @comments = @article.comments.order("created_at") if @article.present?
  end

  # GET /articles/new
  def new
    @journal = Journal.find(params[:id])
    @article = @journal.articles.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find_by_id(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:title, :body, :author, :journal_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  # def index
  #   @comments = Comment.all
  # end

  # GET /comments/1
  # GET /comments/1.json
  # def show
  # end

  # GET /comments/new
  def new
    @comment = Comment.new(:parent_id => params[:parent_id],:article_id => params[:article_id])
  end

  # GET /comments/1/edit
  # def edit
  # end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        @article = Article.find_by_id(params[:comment][:article_id])
        @comments = @article.comments.order("created_at") if @article.present?
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js{}
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js{}
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  # def update
  #   respond_to do |format|
  #     if @comment.update(comment_params)
  #       format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @comment }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      @article = Article.find_by_id(params[:article_id])
      @comments = @article.comments.order("created_at") if @article.present?
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
      format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:body,:article_id,:parent_id)
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy,:articles]

  # GET /journals
  # GET /journals.json
  def index
    @journals = current_user.journals
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = current_user.journals.new(journal_params)
    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: 'Journal was successfully created.' }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to journals_url, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def articles
   if @journal.present?
    @articles = @journal.articles
   end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_journal
    @journal = Journal.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def journal_params
    params.require(:journal).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:ul, nested_comments(sub_comments), :class => "nested_comments")
    end.join.html_safe
  end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/articles/_display_comments.html.erb
<div class="tree well">
  <ul>
    <%= nested_comments @comments.arrange(:order => :created_at) %>
  </ul>
</div>

app/views/articles/_form.html.erb
<div class="col-lg-8">
<%= form_for @article, :class=> "form-horizontal" do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <label for="title" class="col-sm-2 control-label">Title</label>
    <%= f.text_field :title, :class=> "form-control" %>
  </div>
  <div class="form-group">
    <label for="body" class="col-sm-2 control-label">Body</label>
    <%= f.text_area :body, :class=> "form-control" %>
  </div>
  <div class="form-group">
    <label for="author" class="col-sm-2 control-label">Author</label>
    <%= f.text_field :author, :class=> "form-control" %>
  </div>
    <%= f.hidden_field :journal_id %><br>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Create Article", :class=> "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/articles/_message.html.erb
<li>
  <span><i class="icon-minus-sign"></i> Child</span> <a href="#" data-toggle="modal" data-target=".comment_modal">Reply</a>
  <ul>
    <li>
      <span><i class="icon-leaf"></i> Grand Child</span> <a href="#" data-toggle="modal" data-target=".comment_modal">Reply</a>
    </li>
    <li>
      <span><i class="icon-leaf"></i> Grand Child</span> <a href="#" data-toggle="modal" data-target=".comment_modal">Reply</a>
    </li>
  </ul>
</li>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Articles</h1>
<%= content_tag(:p,"No Articles found",class: :strong) if @articles.empty? %>
<ul>
  <% @articles.each do |article| %>
    <li><%= link_to article.title, article %></li>
    </tr>
  <% end %>
</ul>

<br>

<%= link_to 'View Magazine', journals_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<div class="col-lg-12">
  <%= render 'form' %>
</div>
<div class="col-lg-12">
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<% if @article.present? %>
    <div class="col-lg-12">
      <div class="jumbotron">
        <h2 class="text-center"><%= @article.title %></h2>
        <p>
          <br/>
          <%= @article.body %>
        </p>
        <p class="pull-right">
          <strong>By:</strong>
          <%= @article.author %>
        </p>
        <p>
          <strong>Magazine:</strong>
          <%= @article.journal.name %>
        </p>
        <p><%= link_to 'Edit Article', edit_article_path(@article),:class=>"btn btn-primary pull-right" %></p>
      </div>
    </div>
    <div class="col-lg-12" id="comment_div">
      <%= render "display_comments" unless @comments.empty? %>
    </div>
    <div class="col-lg-12">
      <%= link_to "Comment Article", new_comment_path(:article_id => @article.id),:class => "btn btn-primary", :remote => "true" %>
      <div class="modal fade comment_modal" id="comment_modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="gridSystemModalLabel"><%= "#{@article.title}" %></h4>
            </div>
            <div class="modal-body">
              <div class="container-fluid">
                <div class="row" id="comment_form">
                  <%= render "comments/form" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<% else %>
    <p class="alert alert-error"><%= "Article Not Found" %></p>
<% end %>

app/views/comments/_comment.html.erb
<li>
  <span><i class="icon-folder-open"></i> <%= comment.body %></span> <%= link_to "Reply", new_comment_path(:parent_id => comment,:article_id => comment.article_id), :remote => "true" %>
  <% if comment.descendants.count <= 0 %>
      | <%= link_to "Destroy", comment_path(:id => comment.id,:article_id => comment.article_id), :confirm => "Are you sure?", :remote => "true",:method => :delete %>
  <% end %>
</li>

app/views/comments/_form.html.erb
<%=form_for @comment, :html => {:class=>"form-inline",:remote => true } do |f| %>
  <%= f.hidden_field :parent_id %>
  <%= f.hidden_field :article_id %>
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon">Comment</div>
      <%= f.text_field :body, :class => "form-control" %>
	    </div>
  </div>
  <%= f.submit "Post Comment",:class=>"btn btn-primary" %>
<% end %>

app/views/comments/create.js.erb
<% if @comments.present? %>
$("#comment_div").html("<%= j render 'articles/display_comments' %>");
$('#comment_modal').modal('hide');
<% else %>
alert("<%= @comment.errors.full_messages.join(",").html_safe %>");
$('#comment_modal').modal('hide');
<% end %>

app/views/comments/destroy.js.erb
$("#comment_div").html("<%= j render 'articles/display_comments' %>");

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/new.js.erb
$("#comment_form").html("<%= j render 'form' %>");
$('#comment_modal').modal('show');

app/views/journals/_form.html.erb
<%= form_for @journal, :html => {:class => "form-inline"} do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>
      <ul>
      <% @journal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <label for="name">Name:</label>
	  <%= f.text_field :name ,:class => "form-control"%>
  </div>
    <%= f.submit "Create Magazine", :class => "btn btn-default" %>
<% end %>

app/views/journals/articles.html.erb
<br/>
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Articles</div>
  <div class="panel-body">
    <% if @articles.present? %>
      <ul class="list-group">
        <% @articles.each do |article|%>
          <li class="list-group-item"><%= article.title %></li>
        <% end %>
      </ul>
    <% else %>
      <p> No Articles Found. </p>
    <% end%>
  </div>
  <div class="panel-footer"><%= "#{@articles.count rescue 0} " %> Articles for Magazine <%= @journal.name rescue "" %> <%= content_tag(:span ,(link_to "New Article", new_article_path(@journal)), :class => "label new_article_link label-success pull-right" ) if @journal.present? %> </div>
</div>

app/views/journals/edit.html.erb
<h1>Editing Journal</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Show', @journal %> |
<%= link_to 'Back', journals_path %>

app/views/journals/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Magazines</h2>
<%= content_tag(:p,"No Magazine Found") if @journals.empty? %>
<ul class="list-group" >
  <% @journals.each do |journal| %>
    <li class="list-group-item" > <%= link_to journal.name, journal %>  <%= link_to "View/Create Articles", articles_journal_path(journal), :class=> "pull-right"%>
      <%#= link_to 'Destroy', journal, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>
<br>

<%= link_to 'New Magazine', new_journal_path, :class =>"btn btn-default" %>

app/views/journals/new.html.erb
<h1>New Magazine</h1>

<%= render 'form' %><br/>

<%= link_to 'Back', journals_path %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>
<p> Journal Name </p>
<strong><%= @journal.name %></strong>
<br/>
<%= link_to 'Edit', edit_journal_path(@journal) %> |
<%= link_to 'Back', journals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magazine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <% if user_signed_in? %>
    <div class="col-lg-12">
      <%= link_to('Logout', destroy_user_session_path, :method => :delete,:class=> "pull-right") %>
    </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>